DROP TABLE IF EXISTS SKILL_TYPE;
CREATE TABLE SKILL_TYPE(
	SKILL_TYPE_ID NUMBER(10) PRIMARY KEY,
	SKILL_TYPE_NAME VARCHAR(30) ,
	IS_ACTIVE NUMBER(1)
);

DROP SEQUENCE IF EXISTS SKILL_TYPE_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS SKILL_TYPE_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 1;

INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'COOKLEY',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'OTCOM',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'FLEXIDY',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'SPAN',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'KANLAM', 1);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'ALPHAZAP',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'SONSING', 1);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'ZAMIT', 1);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'SUBIN',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'TRANSCOF',0);
INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, IS_ACTIVE) VALUES (SKILL_TYPE_SEQUENCE.NEXTVAL,'BITWOLF',0);

DROP TABLE IF EXISTS SKILL_TYPE_BUCKET_LOOKUP;
CREATE TABLE SKILL_TYPE_BUCKET_LOOKUP(
	SKILL_TYPE_BUCKET_LOOKUP_ID NUMBER(10) PRIMARY KEY,
	SKILL_TYPE_ID NUMBER(10),
	BUCKET_ID NUMBER(10),
	WEIGHT NUMBER,
);

DROP SEQUENCE IF EXISTS SKILL_TYPE_BUCKET_LOOKUP_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS SKILL_TYPE_BUCKET_LOOKUP_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 1;

INSERT INTO SKILL_TYPE_BUCKET_LOOKUP (SKILL_TYPE_BUCKET_LOOKUP_ID, SKILL_TYPE_ID, BUCKET_ID, WEIGHT) VALUES (SKILL_TYPE_BUCKET_LOOKUP_SEQUENCE.NEXTVAL,2,3,30);
INSERT INTO SKILL_TYPE_BUCKET_LOOKUP (SKILL_TYPE_BUCKET_LOOKUP_ID, SKILL_TYPE_ID, BUCKET_ID, WEIGHT) VALUES (SKILL_TYPE_BUCKET_LOOKUP_SEQUENCE.NEXTVAL,2,1,70);
INSERT INTO SKILL_TYPE_BUCKET_LOOKUP (SKILL_TYPE_BUCKET_LOOKUP_ID, SKILL_TYPE_ID, BUCKET_ID, WEIGHT) VALUES (SKILL_TYPE_BUCKET_LOOKUP_SEQUENCE.NEXTVAL,3,1,50);
INSERT INTO SKILL_TYPE_BUCKET_LOOKUP (SKILL_TYPE_BUCKET_LOOKUP_ID, SKILL_TYPE_ID, BUCKET_ID, WEIGHT) VALUES (SKILL_TYPE_BUCKET_LOOKUP_SEQUENCE.NEXTVAL,3,2,50);

COMMIT;